mtum/mtum/urls.py
from django.conf.urls import patterns, include, url
# from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # url(r'^$', TemplateView.as_view(template_name='base.html')),

    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns(
    'account.views',
    url(r'^register$', 'register', name='register'),
    url(r'^login$', 'login', name='login'),
    url(r'^logout$', 'logout', name='logout'),
    url(r'^forgot_password$', 'forgot_password', name='forgot_password'),
    url(r'^account/delete$', 'delete_account', name='delete_account'),
)

urlpatterns += patterns(
    'dashboard.views',
    url(r'^$', 'index', {'keyword': ''}, name='index'),
    url(r'^search$', 'search', name='search'),
    url(r'^tagged/(?P<keyword>[-\w]+)$', 'index', name='tagged'),

    url(r'^dashboard$', 'dashboard', name='dashboard'),
    url(r'^mine$', 'dashboard', {'posts_filter': 'mine'}, name='mine'),
    url(r'^likes$', 'dashboard', {'posts_filter': 'likes'}, name='likes'),
    url(r'^following$', 'dashboard', {'posts_filter': 'following'},
        name='following'),
    url(r'^followers$', 'followers', name='followers'),

    url(r'^new/text$', 'new_text', name='new_text'),
    url(r'^new/photo$', 'new_photo', name='new_photo'),
    url(r'^new/video$', 'new_video', name='new_video'),
    url(r'^edit/(?P<post_id>\d+)$', 'edit_post', name='edit_post'),
    url(r'^delete/(?P<post_id>\d+)$', 'delete_post', name='delete_post'),
)

urlpatterns += patterns(
    'dashboard.views_settings',
    url(r'^settings$', 'account', name='settings'),
)

urlpatterns += patterns(
    'message.views',
    url(r'^inbox$', 'inbox', name='inbox'),
    url(r'^send$', 'send', name='send'),
    url(r'^send/(?P<sender_slug>[-\w+]+)/from/(?P<recipient_slug>[-\w+]+)/reply/(?P<message_id>\d+)$',
        'reply', name='reply'),
    url(r'^deny_submission/(?P<message_id>\d+)$', 'deny', name='deny'),
    url(r'^messages/purge$', 'deny', {'purge': True}, name='purge'),
)

urlpatterns += patterns(
    'post.views',
    url(r'^like/(?P<post_id>\d+)$', 'like', name='like'),
    url(r'^unlike/(?P<post_id>\d+)$', 'unlike', name='unlike'),
    url(r'^reblog/(?P<post_id>\d+)$', 'reblog', name='reblog'),
    url(r'^follow/(?P<user_slug>[-\w+]+)$', 'follow', name='follow'),
    url(r'^unfollow/(?P<user_slug>[-\w+]+)$', 'unfollow', name='unfollow'),

    url(r'^blog/(?P<user_slug>[-\w]+)$', 'user_index', name='user_index'),
    url(r'^blog/(?P<user_slug>[-\w]+)/tagged/(?P<tag_slug>[-\w]+)$',
        'user_index', name='user_tag'),
    url(r'^blog/(?P<user_slug>[-\w]+)/random$', 'random_post', name='random'),

    url(r'^blog/(?P<user_slug>[-\w]+)/search$', 'user_search',
        name='user_search'),
    url(r'^blog/(?P<user_slug>[-\w]+)/search/(?P<keyword>[-\+\w]+)$',
        'user_search_result', name='user_search_result'),

    url(r'^blog/(?P<user_slug>[-\w]+)/post/(?P<post_id>\d+)$',
        'detail', name='post_detail'),
    url(r'^blog/(?P<user_slug>[-\w]+)/post/(?P<post_id>\d+)/'
        + r'(?P<post_slug>[-\w]+)$', 'detail', name='post_detail_slug'),
)

mtum/dashboard/models.py
from django.db import models

# Create your models here.

mtum/post/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from unidecode import unidecode


class Tag(models.Model):
    KIND_CHOICES = (
        ('F', 'featured'),
        ('N', 'normal'),
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    kind = models.CharField(max_length=1, choices=KIND_CHOICES, default='N')
    # user = models.ManyToManyField(User)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super(Tag, self).save(*args, **kwargs)


class Post(models.Model):
    KIND_CHOICES = (
        ('T', 'text'),
        ('P', 'photo'),
        ('Q', 'quote'),
        ('L', 'link'),
        ('C', 'chat'),
        ('A', 'audio'),
        ('V', 'video'),
    )
    author = models.ForeignKey(User)
    slug = models.SlugField(max_length=300, null=True, blank=True)

    source = models.URLField(null=True, blank=True)
    title = models.CharField(max_length=300, null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    quote = models.TextField(null=True, blank=True)
    photo = models.URLField(null=True, blank=True)
    video = models.CharField(max_length=500, null=True, blank=True)
    content = models.TextField(null=True, blank=True)

    kind = models.CharField(max_length=1, choices=KIND_CHOICES)
    tags = models.ManyToManyField(Tag, related_name='tags')
    created_at = models.DateTimeField(auto_now_add=True)
    reblog = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return '%s-%s' % (str(self.id), self.title or '')

    def save(self, *args, **kwargs):
        if (not self.slug) and self.title:
            self.slug = slugify(unidecode(self.title))
        super(Post, self).save(*args, **kwargs)


class Like(models.Model):
    author = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s-%s' % (str(self.post.id), self.post.title or '')


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='follower')
    following = models.ForeignKey(User, related_name='following')
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.follower.username

mtum/dashboard/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms


class TextForm(forms.Form):
    attrs_title = {
        'class': 'text_field big wide',
    }
    attrs_content = {
        'class': 'wide post_two',
    }
    attrs_tags = {
        'class': 'text_field',
    }

    title = forms.CharField(required=False,
                            widget=forms.TextInput(attrs=attrs_title))
    content = forms.CharField(widget=forms.Textarea(attrs=attrs_content))
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs=attrs_tags))
    post_id = forms.IntegerField(widget=forms.HiddenInput, required=False)


class PhotoForm(forms.Form):
    attrs_photo = {
        'class': 'text_field wide',
    }
    attrs_content = {
        'class': 'wide post_caption',
    }
    attrs_tags = {
        'class': 'text_field',
    }

    title = forms.CharField(required=False)
    photo = forms.URLField(widget=forms.TextInput(attrs=attrs_photo))
    url = forms.URLField(required=False,
                         widget=forms.TextInput(attrs=attrs_photo))
    content = forms.CharField(required=False,
                              widget=forms.Textarea(attrs=attrs_content))
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs=attrs_tags))
    post_id = forms.IntegerField(widget=forms.HiddenInput, required=False)


class QuoteForm(forms.Form):
    pass


class LinkForm(forms.Form):
    title = forms.CharField(required=False)
    url = forms.URLField()
    content = forms.CharField(widget=forms.Textarea, required=False)
    tags = forms.CharField(required=False)


class ChatForm(forms.Form):
    pass


class AudioForm(forms.Form):
    pass


class VideoForm(forms.Form):
    attrs_video = {
        'class': 'text_field wide',
    }
    attrs_content = {
        'class': 'wide post_caption',
    }
    attrs_tags = {
        'class': 'text_field',
    }

    title = forms.CharField(required=False)
    video = forms.URLField(widget=forms.TextInput(attrs=attrs_video))
    content = forms.CharField(required=False,
                              widget=forms.Textarea(attrs=attrs_content))
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs=attrs_tags))
    post_id = forms.IntegerField(widget=forms.HiddenInput, required=False)


class AccountForm(forms.Form):
    attrs_input = {
        'class': 'text_field',
    }
    attrs_email = {
        'class': 'text_field',
        'style': 'width: 392px;',
    }

    email = forms.EmailField(widget=forms.TextInput(attrs=attrs_email))
    c_password = forms.CharField(required=False,
                                 widget=forms.PasswordInput(attrs=attrs_input))
    n_password = forms.CharField(required=False,
                                 widget=forms.PasswordInput(attrs=attrs_input))
    m_password = forms.CharField(required=False,
                                 widget=forms.PasswordInput(attrs=attrs_input))
    title = forms.CharField(widget=forms.TextInput(attrs=attrs_input),
                            required=False)
    description = forms.CharField(widget=forms.Textarea(attrs=attrs_email),
                                  required=False)

mtum/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="" class="no_js logged_in tab_switcher_safari" id="logged_in">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=960" id="viewport">
    <meta http-equiv="x-dns-prefetch-control" content="off">
    <title> Tumblr </title>
    <link ilo-ph-fix="tofix" alt="[Image]" ilo-full-src="http://assets.tumblr.com/favicon.ico?3" rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="http://assets.tumblr.com/images/apple_touch_icon.png?2">
    <meta name="application-name" content="Tumblr">
    <meta name="msapplication-TileColor" content="#2c4762">
    <meta name="msapplication-TileImage" content="http://assets.tumblr.com/images/msfavicon.png">
    <meta name="apple-itunes-app" content="app-id=305343404,app-argument=tumblr://x-callback-url/dashboard?referrer=smart-app-banner">
    <!-- <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/site.css" media="all"> -->
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/dashboard.css" media="all">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/global.css" media="all">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/index.css" media="all">
    {% endblock %}
  </head>
  <body id="dashboard_index" class="dashboard_index logged_in with_auto_paginate is_dashboard layout_standard" data-form-key="fdx8oYTujh4LqC7u3sz98ZmuoQw" data-new-root="" data-page-root="/dashboard"><img ilo-ph-fix="tofix" style="position: absolute; z-index: -3334; top: 0px; left: 0px; visibility: hidden;" src="impixu">    

    <div data-token="body-plexi" class="plexi color"></div>

    {% block header %}
      {% include "header.html" %}
    {% endblock %}

    {% block main %}
    {% endblock %}


    <div id="footer_container" class="clearfix">
      {% include "footer.html" %}
    </div>
  </div>

  {% block others %}
  {% endblock %}

  {% block js %}
  {% endblock %}
</body>
</html>

mtum/templates/dashboard/followers.html
{% extends "dashboard/base.html" %}
{% load url from future %}
{% load endless %}
{% load account_extras %}
{% load dashboard_extras %}


{% block css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/following.css?002" media="all">
{% endblock %}


{% block main %}
<div id="content" class="clearfix">

  <div class="followers" id="left_column">
    <div class="white_pane">

    <div class="title_and_controls">
        <h1>{{ user|follower_numbers }} person is following you</h1>
        <div class="white_pane_controls">
        </div>
    </div>

    <div class="followers">

      {% for follower in followers %}
      {% with username=follower.username %}
      <div class="follower alt clearfix">
        <a style="background-image: url('{{ follower|get_avatar:40 }}');" class="avatar" href="{{ follower|get_blog_url }}"><img width="40" height="40" src="{{ follower|get_avatar:40 }}" alt="" class="avatar_img"></a>
        <div class="info">
          <div class="name"><a href="{{ follower|get_blog_url }}">{{ username }}</a></div>
          <div class="description"><a data-user-name="{{ username }}" class="ignore" href="#">ignore</a></div>
        </div>
        {% if not user|is_following:follower %}
        <div class="controls" id="controls_{{ username }}">
          <span style="display: none;" class="loading_animation" id="loading_{{ username }}"></span>
          {% url 'follow' follower.get_profile.slug as follow_url %}
          <a href="{{ follow_url }}" onclick="follow('{{ follow_url }}', '#controls_{{ username }}', '#loading_{{ username }}'); return false;"><button id="follow_button_{{ follower.id }}" class="chrome blue big follow_button" data-user-name="{{ username }}" data-form-key="">Follow</button></a>
        </div>
        {% endif %}
      </div>
      {% endwith %}
      {% endfor %}

    </div>

    <div class="clear"></div>
  </div>
</div>

{% include "dashboard/sidebar.html" %}

</div>
{% endblock %}


{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
<script>
  function follow(url, hiden, show) {
    $(hiden).hide();
    $(show).show();
    $.ajax({
      url: url,
      success: function(data) {
        $(show).hide();
      }
    });
  }
</script>
{% endblock %}

mtum/templates/dashboard/new.html
{% extends "dashboard/base.html" %}
{% load url from future %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/global.css" media="all">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/new.css" media="all">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}markitup/skins/markitup/style.css" />
  <link rel="stylesheet" type="text/css" href="{{STATIC_URL }}markitup/sets/markdown/style.css" />
{% endblock %}

{% block main %}

<img id="content_top" src="{{ STATIC_URL}}dashboard/images/content_top_edit_form.png">
<div id="content" class="clearfix">
  <div class="clearfix">
    <form onsubmit="" class="{% if kind == 'text' %}regular_post{% else %}photo_post{% endif %}" id="edit_post" method="post" action="{{ action_url }}"> {% csrf_token %}
      <div style="width: 200px; float: right; margin: 0px 20px 0px 0px;" id="right_column">
        <div id="edit_post_controls">

          <!-- Tumblelog -->

          <!-- Privacy -->
          <!-- <div style="border: medium none; padding: 0px 0px 15px;" class="advanced_option" id="set_privacy"> -->
            <!-- <select onchange="" style="width: 200px;" name="post[state]" id="post_state"> -->
              <!-- <option selected="selected" value="0">publish now</option> -->
              <!-- <option value="2">add to queue</option> -->
              <!-- <option value="on.2">publish on...</option> -->
              <!-- <option value="1">save as draft</option> -->
              <!-- <option value="private">private</option> -->
            <!-- </select> -->
          <!-- </div> -->
          <!-- <div style="border-bottom: medium none;" class="advanced_option_divider"></div> -->

          <!-- <div style="padding-top: 12px; display: none;" class="advanced_option" id="set_publish_on_time"> -->
            <!-- <label style="position: relative; top: -3px;" for="post_publish_on">Publish time:</label> -->
            <!-- <input type="text" style="width: 189px;" name="post[publish_on]" id="post_publish_on" class="text_field" value=""> -->
          <!-- </div> -->

          <!-- <div style="display: none;" class="advanced_option" id="set_status_message"> -->
            <!-- <label onclick="" id="post_draft_status_label" class="inline_input_label" for="post_draft_status">status message</label> -->
            <!-- <input type="text" onfocus="" style="width: 189px;" id="post_draft_status" name="post[draft_status]" class="text_field" value=""> -->
          <!-- </div> -->

          <!-- Date -->
          <!-- <div class="advanced_option" id="set_date"> -->
            <!-- <label onclick="" id="post_date_label" class="inline_input_label" for="post_date">post date</label> -->
            <!-- <input type="text" onfocus="" style="width: 188px;" class="text_field" name="post[date]" value="now" id="post_date"> -->
          <!-- </div> -->

          <!-- Content source -->
          <!-- <div class="advanced_option" id="set_source_url"> -->
            <!-- <div class="source_url_questionmark_gradient"></div> -->
            <!-- <a title="What's this?" class="source_url_questionmark" onclick="" href="#"></a> -->
            <!-- <div style="display: none;" id="source_url_tooltip">The page where the content quoted in this post was originally published (if relevant)<div id="source_url_tooltip_nipple"></div></div> -->
            <!-- <label style="right: 22px;" onclick="" id="post_source_url_label" class="inline_input_label" for="post_source_url">content source</label> -->
            <!-- <input type="text" onblur="" onfocus="" style="width: 188px;" class="text_field" name="post[source_url]" value="http://" id="post_source_url"> -->
          <!-- </div> -->

          <!-- Tags -->
          <div class="advanced_option" id="set_tags">
            <h2>tags</h2>
            <!-- <label style="left: 8px; right: auto; text-align: left;" onclick="" id="post_tags_label" class="inline_input_label" for="post_tags">tags</label> -->
            {{ form.tags }}
          </div>

          <!-- Slug -->
          <!-- <div style="padding-top: 12px;" class="advanced_option" id="set_slug"> -->
            <!-- <label for="post_slug">Set a custom post URL</label> -->
            <!-- <div id="slug_url"> -->
              <!-- /post/123456/<input type="text" onchange="" class="inline_text_field" name="post[slug]" id="post_slug" value=""> -->
            <!-- </div> -->
          <!-- </div> -->

          <!-- Share Options -->
          <!-- <div style="display: none;" id="autopost_options" class="advanced_option"> -->
            <!-- Twitter -->
            <!-- <div style="display: none;" id="set_twitter"> -->
              <!-- <input type="checkbox" checked="checked" name="send_to_twitter" id="send_to_twitter" style="margin-left: 0px; vertical-align: 1px; width: auto;"> -->
              <!-- <label style="display: inline;" for="send_to_twitter">Send to Twitter</label> -->
              <!-- <a onclick="" style=" font:10px 'Lucida Grande',Verdana; color:#bbb; -->
                <!-- margin-left:2px; " id="edit_tweet_link" href="#">edit</a> -->
              <!-- <span id="tweet_length" style="font: bold 10px 'Lucida Grande',Verdana; color: rgb(187, 187, 187); margin-left: 2px;"></span> -->

              <!-- <div id="custom_tweet_container" style="margin-top: 8px; display: none;"> -->
                <!-- <div><textarea class="text_field" style="width: 189px; height: 50px; font: 11px 'Lucida Grande',Verdana; resize: vertical;" onblur="if (! this.value) { $('custom_tweet_container').hide(); clearInterval(check_tweet_length); $('edit_tweet_link').show(); $('tweet_length').innerHTML = ''; }" name="custom_tweet" id="custom_tweet"></textarea><br></div> -->
              <!-- </div> -->

            <!-- </div> -->

            <!-- Facebook -->

            <!-- Short URL -->
          <!-- </div> -->

          <!-- Advanced Options -->

          <!-- Photo Reply -->
          <!-- <div class="advanced_option"> -->
            <!-- <input type="checkbox" name="allow_photo_replies" id="allow_photo_replies" style="margin-left: 0px; vertical-align: 1px; width: auto;"> -->
            <!-- <label style="display: inline;" for="allow_photo_replies">Let people photo reply<img style="vertical-align: -2px; width: 15px; height: 12px; margin-left: 6px; opacity: 0.8;" src="small_camera.png" ilo-full-src="http://assets.tumblr.com/images/small_camera.png" title="http://assets.tumblr.com/images/small_camera.png  file:///D:/Files/%E6%95%B4%E7%AB%99%E4%B8%8B%E8%BD%BD/temp/Tumblr02_files/small_camera.png  file:///D:/Settings/Mozilla/ScrapBook/data/20130213165240/small_camera.png  file:///D:/Settings/Mozilla/ScrapBook/data/20130213165240/small_camera.png"></label> -->
          <!-- </div> -->

          <!-- Answers -->
          <!-- <div style="display: none;" class="advanced_option" id="enable_answers_container"> -->
            <!-- <label for="allow_answers"> -->
              <!-- <input type="checkbox" name="allow_answers" id="allow_answers" style="margin-left: 0px; vertical-align: -2px; width: auto;"> -->
              <!-- Let people answer this -->
            <!-- </label> -->
          <!-- </div> -->

          <!-- <div class="advanced_option last"></div> -->
        </div>
      </div>

      <div style="width: 600px; float: left; padding: 5px 0px 5px 30px;" id="left_column">

        {% if kind == "text" %}
          {% include "dashboard/new_text.html" %}
        {% endif %}
        {% if kind == "photo" %}
          {% include "dashboard/new_photo.html" %}
        {% endif %}
        {% if kind == "video" %}
          {% include "dashboard/new_video.html" %}
        {% endif %}

        <div id="post_controls">

          <button id="cancel_button" class="negative" onclick="" style="float: right;" type="button"> Cancel </button>
          <button style="margin: 0px;" onclick="" id="save_button" class="positive" type="submit">
            <img alt="" src="{{ STATIC_URL }}dashboard/images/check.png" >
            <span id="create_post_button_label"> Create post </span>
          </button>

          <button type="button" style="margin: 0px 0px 0px 15px;" value="Preview" onclick="" id="preview_button" class="generic" name="preview_post"> Preview </button>
          <img style="display: none;" alt="" id="loading" src="{{ STATIC_URL }}dashboard/images/loading.gif" >
        </div>
      </div>
    </form>
    <div class="clear"></div>
  </div>
</div>
<img id="content_bottom" src="{{ STATIC_URL }}dashboard/images/content_bottom_edit_form.png">

{% endblock %}


{% block js %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
  <script src="{{ STATIC_URL }}js/jquery-migrate-1.1.0.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}markitup/jquery.markitup.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}markitup/sets/markdown/set.js"></script>

  <script language="javascript">
  $(document).ready(function(){
      $("#id_content").markItUp(mySettings);
  });
  </script>
{% endblock %}

mtum/templates/dashboard/new_photo.html
<h1> Add a Photo Post
  <img style="display: none;" title="Post is private  http://assets.tumblr.com/images/protected_blog_padlock.png" id="privacy_lock" alt="Private" src="protected_blog_padlock.png" >
</h1>


<!-- editor.js: render_editor() overrides these -->
<input type="hidden" value="0" name="is_rich_text[one]" id="post_one_is_rich_text">
<input type="hidden" value="0" name="is_rich_text[two]" id="post_two_is_rich_text">
<input type="hidden" value="0" name="is_rich_text[three]" id="post_three_is_rich_text">

<input type="hidden" value="fdx8oYTujh4LqC7u3sz98ZmuoQw" name="form_key" id="form_key">


<!-- Photo booth stuff -->
<input type="hidden" id="photo_raw" name="photo_raw">



<div id="booth"></div>
<div style="" id="set_avatar_container"><div style="display: none; font: 10px 'Lucida Grande',Verdana,sans-serif; margin-top: 5px; color: rgb(119, 119, 119); text-align: right; float: right; width: 300px;" id="set_avatar_option"><input type="checkbox" name="set_avatar" id="set_avatar" style="margin-right: 6px; margin-left: 0px;"><label id="set_avatar_label" for="set_avatar">Make this my avatar</label></div></div>

<div style="" id="photo_url">
  <h2>Photo URL</h2>
  {{ form.errors.photo }}
  <div class="text_field_container">{{ form.photo }}</div>
</div>

<input type="hidden" value="10485760" name="MAX_FILE_SIZE">

<h2>Caption <span class="optional">(optional)</span></h2>
<div>{{ form.content }}</div>



<div style="" id="photo_link">
  <h2>Clicking this photo links to the URL: <span class="optional">(optional)</span></h2>
  <div class="text_field_container">{{ form.url }}</div>
</div>

<div>{{ form.post_id }}</div>

mtum/templates/dashboard/new_text.html
<h1> Add a Text Post
  <img style="display: none;" title="Post is private  http://assets.tumblr.com/images/protected_blog_padlock.png" id="privacy_lock" alt="Private" src="protected_blog_padlock.png" >
</h1>


<!-- editor.js: render_editor() overrides these -->
<input type="hidden" value="0" name="is_rich_text[one]" id="post_one_is_rich_text">
<input type="hidden" value="0" name="is_rich_text[two]" id="post_two_is_rich_text">
<input type="hidden" value="0" name="is_rich_text[three]" id="post_three_is_rich_text">
<input type="hidden" value="fdx8oYTujh4LqC7u3sz98ZmuoQw" name="form_key" id="form_key">

<h2 class="first">Title <span class="optional">(optional)</span></h2>
<div class="text_field_container">
  {{ form.title }}
</div>

<div style="height: 30px;"></div>
<h2 style="float: left; margin-top: 0px;">Post</h2>
<div style="float: right; padding-top: 3px;">
</div>
  {{ form.errors.content }}
<div class="clear"></div>

<div>{{ form.content }}</div>

<div>{{ form.post_id }}</div>