mtum/mtum/urls.py
from django.conf.urls import patterns, include, url
# from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # url(r'^$', TemplateView.as_view(template_name='base.html')),

    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns(
    'account.views',
    url(r'^register$', 'register', name='register'),
    url(r'^login$', 'login', name='login'),
    url(r'^logout$', 'logout', name='logout'),
    url(r'^forgot_password$', 'forgot_password', name='forgot_password'),
    url(r'^account/delete$', 'delete_account', name='delete_account'),
)

urlpatterns += patterns(
    'dashboard.views',
    url(r'^$', 'index', {'keyword': ''}, name='index'),
    url(r'^search$', 'search', name='search'),
    url(r'^tagged/(?P<keyword>[-\w]+)$', 'index', name='tagged'),

    url(r'^dashboard$', 'dashboard', name='dashboard'),
    url(r'^mine$', 'dashboard', {'posts_filter': 'mine'}, name='mine'),
    url(r'^likes$', 'dashboard', {'posts_filter': 'likes'}, name='likes'),
    url(r'^following$', 'dashboard', {'posts_filter': 'following'},
        name='following'),
    url(r'^followers$', 'followers', name='followers'),

    url(r'^new/text$', 'new_text', name='new_text'),
    url(r'^new/photo$', 'new_photo', name='new_photo'),
    url(r'^new/video$', 'new_video', name='new_video'),
    url(r'^edit/(?P<post_id>\d+)$', 'edit_post', name='edit_post'),
    url(r'^delete/(?P<post_id>\d+)$', 'delete_post', name='delete_post'),
)

urlpatterns += patterns(
    'dashboard.views_settings',
    url(r'^settings$', 'account', name='settings'),
)

urlpatterns += patterns(
    'message.views',
    url(r'^inbox$', 'inbox', name='inbox'),
    url(r'^send$', 'send', name='send'),
    url(r'^send/(?P<sender_slug>[-\w+]+)/from/(?P<recipient_slug>[-\w+]+)/reply/(?P<message_id>\d+)$',
        'reply', name='reply'),
    url(r'^deny_submission/(?P<message_id>\d+)$', 'deny', name='deny'),
    url(r'^messages/purge$', 'deny', {'purge': True}, name='purge'),
)

urlpatterns += patterns(
    'post.views',
    url(r'^like/(?P<post_id>\d+)$', 'like', name='like'),
    url(r'^unlike/(?P<post_id>\d+)$', 'unlike', name='unlike'),
    url(r'^reblog/(?P<post_id>\d+)$', 'reblog', name='reblog'),
    url(r'^follow/(?P<user_slug>[-\w+]+)$', 'follow', name='follow'),
    url(r'^unfollow/(?P<user_slug>[-\w+]+)$', 'unfollow', name='unfollow'),

    url(r'^blog/(?P<user_slug>[-\w]+)$', 'user_index', name='user_index'),
    url(r'^blog/(?P<user_slug>[-\w]+)/tagged/(?P<tag_slug>[-\w]+)$',
        'user_index', name='user_tag'),
    url(r'^blog/(?P<user_slug>[-\w]+)/random$', 'random_post', name='random'),

    url(r'^blog/(?P<user_slug>[-\w]+)/search$', 'user_search',
        name='user_search'),
    url(r'^blog/(?P<user_slug>[-\w]+)/search/(?P<keyword>[-\+\w]+)$',
        'user_search_result', name='user_search_result'),

    url(r'^blog/(?P<user_slug>[-\w]+)/post/(?P<post_id>\d+)$',
        'detail', name='post_detail'),
    url(r'^blog/(?P<user_slug>[-\w]+)/post/(?P<post_id>\d+)/'
        + r'(?P<post_slug>[-\w]+)$', 'detail', name='post_detail_slug'),
)

mtum/post/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from unidecode import unidecode


class Tag(models.Model):
    KIND_CHOICES = (
        ('F', 'featured'),
        ('N', 'normal'),
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    kind = models.CharField(max_length=1, choices=KIND_CHOICES, default='N')
    # user = models.ManyToManyField(User)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super(Tag, self).save(*args, **kwargs)


class Post(models.Model):
    KIND_CHOICES = (
        ('T', 'text'),
        ('P', 'photo'),
        ('Q', 'quote'),
        ('L', 'link'),
        ('C', 'chat'),
        ('A', 'audio'),
        ('V', 'video'),
    )
    author = models.ForeignKey(User)
    slug = models.SlugField(max_length=300, null=True, blank=True)

    source = models.URLField(null=True, blank=True)
    title = models.CharField(max_length=300, null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    quote = models.TextField(null=True, blank=True)
    photo = models.URLField(null=True, blank=True)
    video = models.CharField(max_length=500, null=True, blank=True)
    content = models.TextField(null=True, blank=True)

    kind = models.CharField(max_length=1, choices=KIND_CHOICES)
    tags = models.ManyToManyField(Tag, related_name='tags')
    created_at = models.DateTimeField(auto_now_add=True)
    reblog = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return '%s-%s' % (str(self.id), self.title or '')

    def save(self, *args, **kwargs):
        if (not self.slug) and self.title:
            self.slug = slugify(unidecode(self.title))
        super(Post, self).save(*args, **kwargs)


class Like(models.Model):
    author = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s-%s' % (str(self.post.id), self.post.title or '')


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='follower')
    following = models.ForeignKey(User, related_name='following')
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.follower.username

mtum/templates/index/base.html
{% load url from future %}
<!DOCTYPE html>
<html lang="" id="logged_out" class="no_js logged_out tab_switcher_safari">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=960" id="viewport">
    <meta http-equiv="x-dns-prefetch-control" content="off">
    <title> Tumblr </title>
    <link ilo-ph-fix="tofix" alt="[Image]" ilo-full-src="https://secure.assets.tumblr.com/favicon.ico?3" rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="https://secure.assets.tumblr.com/images/apple_touch_icon.png?2">
    <meta name="application-name" content="Tumblr">
    <meta name="msapplication-TileColor" content="#2c4762">
    <meta name="msapplication-TileImage" content="https://secure.assets.tumblr.com/images/msfavicon.png ">
    <meta name="apple-itunes-app" content="app-id=305343404,app-argument=tumblr://x-callback-url/dashboard?referrer=smart-app-banner">
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/global.css?0000001" media="all">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/index.css?0000001" media="all">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/global_index.css?0000001" media="all">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}dashboard/hello_tags.css?0000001" media="all">
    {% endblock %}
  </head>
  <body id="account_login_and_register" class="account_login_and_register logged_out without_auto_paginate hello_dash layout_onboarding logged_out" data-form-key="!1231360140853|xV2u2cN1ftBd5JuJlkb173hFZo"><img title="http://www.tumblr.com/impixu?T=1360140853&amp;J=eyJ0eXBlIjoidXJsIiwidXJsIjoiaHR0cDpcL1wvd3d3LnR1bWJsci5jb21cL3JlZ2lzdGVyIn0=&amp;U=IBLDIEECGD&amp;K=a38bacb8c982a0021e3ec501fe314e27d6784212966b1c908734620a86079a97" ilo-ph-fix="tofix" alt="[Image]" ilo-full-src="http://www.tumblr.com/impixu?T=1360140853&amp;J=eyJ0eXBlIjoidXJsIiwidXJsIjoiaHR0cDpcL1wvd3d3LnR1bWJsci5jb21cL3JlZ2lzdGVyIn0=&amp;U=IBLDIEECGD&amp;K=a38bacb8c982a0021e3ec501fe314e27d6784212966b1c908734620a86079a97" style="position: absolute; z-index: -3334; top: 0px; left: 0px; visibility: hidden;" src="impixu">    


    <div class="logged_out_container" id="logged_out_container">

    {% include "index/header.html" %}

    <div class="outter_wrapper">

      <div id="container">
        <div id="content" class="clearfix"><img title="https://secure.assets.tumblr.com/images/content_top.png?alpha" ilo-ph-fix="tofix" ilo-full-src="https://secure.assets.tumblr.com/images/content_top.png?alpha" src="content_top.png" alt="" class="content_cap" id="content_top">


        {% block main %}

        {% endblock %}


        <div class="clear"></div>
        </div>
      <img title="https://secure.assets.tumblr.com/images/content_bottom.png?alpha" ilo-ph-fix="tofix" ilo-full-src="https://secure.assets.tumblr.com/images/content_bottom.png?alpha" src="content_bottom.png" alt="" class="content_cap" id="content_bottom">
      </div>


      {% block js %}
      {% endblock %}


    {% block footer %}
      {% include "footer.html" %}
    {% endblock %}

    </div>
  </body>
</html>

mtum/templates/index/display_posts.html
{% load url from future %}
{% load dashboard_extras %}
{% load markup %}

<div data-animated-gif="false" data-tumblelog="hyperform" data-id="{{ post.id }}" data-grow-height="403" data-grow-width="323" data-effect="grow" data-lightbox="true" data-type="photo"
  class="ht_post {{ post.get_kind_display }} {% if post.kind == 'P' %}not_expanded {% endif %}
  {% if post.tags.all %}has_tags {% endif %} {% if post.kind == 'T' %}box {% endif %}" id="ht_post_{{ post.id }}">

  {% if post.kind == 'P' %}
  <div style="background-image: url('{{ post.photo }}');" class="stage">
    <div class="bg-image-fallback">
      <img src="{{ post.photo }}">
    </div>
    <!-- <a target="_top" href="{{ third.link|default:'#' }}" class="go"></a> -->
    <a target="_top" href="{% url 'post_detail' post.author.get_profile.slug post.id %}" class="go"></a>
  </div>
  {% endif %}
  {% if post.kind == 'T' %}
  <div class="stage">
    <div class="overfade"></div>
    <div class="content">
      {{ post.content|at_link|markdown:"safe" }}
    </div>
    <a target="_blank" href="{% url 'post_detail' post.author.get_profile.slug post.id %}" class="go"></a>
    </div>
  {% endif %}
</div>

{% if post.tags.all %}
<div class="ht_controls">
  <div class="tags">
    <ul>
      {% for tag in post.tags.all %}
      {% if tag.kind == "F" %}
      <li><a class="hello_tag featured" href="{% url 'tagged' tag.slug %}"><span>#</span>{{ tag.name }}</a></li>
      {% else %}
      <li><a class="hello_tag" href="{% url 'tagged' tag.slug %}"><span>#</span>{{ tag.name }}</a></li>
      {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>
{% endif %}

mtum/templates/index/header.html
{% load url from future %}
{% load account_extras %}


{% if is_login %}

      <!--<div id="header_container">-->
      <div class="logged_out_header" id="header">
        <!--<div id="header">-->
          <!-- <h1 id="logo" class="logo "><a href="{% url 'dashboard' %}" class="logo_anchor">Tumblr</a></h1> -->
          <h1 id="logo" class="logo "><a href="/" class="logo_anchor">Tumblr</a></h1>
          <div id="tabs_outter_container">
            <div class="tab_bar" id="user_tools">
              <div class="tab iconic" id="home_button">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <span class="tab_notice new_post_notice_container" id="new_post_notice_container" style="display: none;"><span class="tab_notice_value"></span><span class="tab_notice_nipple"></span></span>
                <div class="selection_nipple"></div>
              </div>
              <div class="tab iconic " id="inbox_button">
                <a href="{% url 'inbox' %}">Inbox</a>
                <div class="selection_nipple"></div>
              </div>
              <div class="tab iconic" id="help_button">
                <a href="#help">Help</a>
                <div class="selection_nipple white"></div>
              </div>
              <div class="tab iconic" id="preferences_button">
                <a href="{% url 'settings' %}">Preferences</a>
                <div class="selection_nipple white"></div>
              </div>
              <div class="tab iconic" id="logout_button">
                <a href="{% url 'logout' %}" onclick="return confirm('Are you sure you want to log out?');">Log out</a>
              </div>

              <div class="tab iconic " id="search_field">
                <form method="get" action="{% url 'search' %}" id="search_form" class="search_form " data-form-key="fdx8oYTujh4LqC7u3sz98ZmuoQw" data-tag-slug="">
                  <input name="scope" id="search_scope" value="all_of_tumblr" type="hidden">
                  <input id="search_query_submit" value="Search tags" type="submit">
                  <input tabindex="1" name="q" value="{{ keyword }}"id="search_query" placeholder="Search tags" value="" class="popover_button" autocomplete="off" type="text">
                </form>
                <div class="selection_nipple"></div>
              </div>


              <div id="popover_tracked_tags" class="popover popover_menu popover_gradient tracked_tags_popover" style="display: none;">
                <div class="popover_inner">
                  <div class="autocomplete_results"></div>
                  <div class="tracked_tags">
                  </div>
                  <div class="related_tags"></div>
                  <div class="popover_menu_item ender">
                    <a href="#explore" tabindex="1">Explore more tags</a>
                  </div>
                </div>
              </div>
          </div>
        </div>
    <!--</div>-->
  </div>

{% else %}

      <div class="logged_out_header" id="header">
        <h1 id="logo" class="logo "><a href="/" class="logo_anchor">Tumblr</a></h1>

        <h2 style="" id="signup_subhead" class="signup_subhead"><span id="signup_subhead_content">Follow the world’s creators.</span></h2>
        <div class="logged_out_search tab" id="search_field">
          <form method="get" action="{% url 'search' %}" id="search_form" class="search_form " data-form-key="EdAkyWKngGPYbMJJQ26uXofYB0" data-tag-slug="">
            <input name="scope" id="search_scope" value="all_of_tumblr" type="hidden">
            <input id="search_query_submit" value="Search tags" type="submit">    <input tabindex="1" name="q" id="search_query" placeholder="Search tags" value="{{ keyword }}" class="popover_button" autocomplete="off" type="text">
        </form>
      </div>

        <div class="signup_buttons">
          <a href="{% url 'login' %}" id="signup_button_login" class="login_signup_button chrome shallow login">Log in</a>
          <a href="/" id="signup_button_cancel" class="login_signup_button chrome shallow cancel">Cancel</a>
          <a href="{% url 'register' %}" id="signup_button_signup" class="login_signup_button chrome other_blue signup">Sign up</a>
        </div>
      </div>
{% endif %}

mtum/templates/index/index.html
{% extends "index/base.html" %}
{% load url from future %}
{% load endless %}
{% load dashboard_extras %}


{% block main %}
<!-- Hello dash -->
<div id="hello_tags" class="clearfix">


  <div class="endless_page_template">
    {% include "index/index_page.html" %}
  </div>

  <div class="clear"></div>
</div>
{% endblock %}


{% block js %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
  <script src="{{ STATIC_URL }}js/jquery-migrate-1.1.0.min.js"></script>
  <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
  <script>
      $.endlessPaginate({
          paginateOnScroll: true,
          paginateOnScrollMargin: 50
          // paginateOnScrollChunkSize: 1
      });
  </script>
{% endblock %}


{% block footer %}
  {% paginate 3 posts_group %}
  {% get_pages %}
  {% if keyword %}
  <style>
    .endless_loading {
      color: #2C4762;
    }
  </style>
  <div id="auto_pagination_loader" {% if not pages.next %}style="display:none;"{% endif %}>
      <span id="auto_pagination_loader_loading">
          <div class="spinner"></div>
          Loading more posts...    </span>

      <span style="display: none;" id="auto_pagination_loader_failure">
          Sorry, we couldn't load the next page!&nbsp; <a onclick="Tumblr.AutoPaginator.start(); return false;" href="#">Try again</a>.    </span>

      <span style="display: none;" id="auto_pagination_loader_no_posts">
          Sorry, we couldn't find any more posts!    </span>
  </div>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

mtum/templates/index/index_page.html
{% load endless %}

{% paginate 3 posts_group %}

{% for first, second, third in posts_group %}
<div class="hello_row">
  <div class="unit sel first_in_row out_controls"><!-- Photo -->
    {% include "index/display_posts.html" with post=first %}
  </div>

  <div class="unit sel out_controls"><!-- Photo -->
    {% include "index/display_posts.html" with post=second %}
  </div>

  <div class="unit sel last_in_row out_controls"><!-- Photo -->
    {% include "index/display_posts.html" with post=third %}
  </div>
</div>
{% endfor %}

{% if keyword %}
{% show_more %}
{% endif %}